import api from './axios'

export const godAPI = {
  getStats: () => api.get('/god/stats/'),
  listOrganizations: () => api.get('/god/organizations/'),
  createOrganization: (payload) => api.post('/god/organizations/', payload),
  getOrganization: (id) => api.get(`/god/organizations/${id}/`),
  updateOrganization: (id, payload) => api.put(`/god/organizations/${id}/`, payload),
  deleteOrganization: (id) => api.delete(`/god/organizations/${id}/`),
  patchPlan: (id, plan) => api.patch(`/god/organizations/${id}/plan/`, { plan }),
  patchSuspend: (id, isActive) => api.patch(`/god/organizations/${id}/suspend/`, { is_active: isActive }),
  listUsers: () => api.get('/god/users/'),
  createUser: (payload) => api.post('/god/users/', payload),
  getUser: (id) => api.get(`/god/users/${id}/`),
  updateUser: (id, payload) => api.put(`/god/users/${id}/`, payload),
  deleteUser: (id) => api.delete(`/god/users/${id}/`),
  resetUserPassword: (id, newPassword) => api.patch(`/god/users/${id}/reset-password/`, { new_password: newPassword }),

  getGodModeOverview: () => api.get('/god/god-mode/overview/'),
  simulateExamAction: (payload) => api.post('/god/god-mode/exam-simulation/', payload),
  simulateAntiCheat: (payload) => api.post('/god/god-mode/anti-cheat/', payload),
  simulateRoleAccess: (payload) => api.post('/god/god-mode/role-access/', payload),
  runApiMonitor: (payload = { run_full_suite: true }) => api.post('/god/god-mode/api-monitor/', payload),
  getDatabaseInspector: () => api.get('/god/god-mode/database-inspector/'),
  listGodModeToggles: () => api.get('/god/god-mode/toggles/'),
  patchGodModeToggle: (key, isEnabled) => api.patch(`/god/god-mode/toggles/${key}/`, { is_enabled: isEnabled }),
  listGodModeLogs: (params = {}) => api.get('/god/god-mode/logs/', { params }),
  createGodModeLog: (payload) => api.post('/god/god-mode/logs/', payload),
  exportGodModeLogs: (params = {}) => api.get('/god/god-mode/logs/export/', { params, responseType: 'blob' }),
  runStressTest: (payload) => api.post('/god/god-mode/stress-test/', payload),
  listGodModeBugReports: () => api.get('/god/god-mode/bug-reports/'),
  createGodModeBugReport: (payload) => api.post('/god/god-mode/bug-reports/', payload),
  patchGodModeBugReport: (id, payload) => api.patch(`/god/god-mode/bug-reports/${id}/`, payload),
  listGodModeSettings: () => api.get('/god/god-mode/settings/'),
  patchGodModeSettings: (payload) => api.patch('/god/god-mode/settings/', payload),
  simulateGodModeNotification: (payload) => api.post('/god/god-mode/notification-simulation/', payload),
}
