from django.urls import path

from apps.attempts.views import (
    AttemptAnswersView,
    AutoSubmitAttemptView,
    AvailableExamsView,
    PlaygroundGenerateView,
    PlaygroundSessionDetailView,
    PlaygroundSessionListView,
    PlaygroundSubmitView,
    PlaygroundSummaryView,
    RemainingTimeView,
    RunCodingAnswerView,
    StartExamView,
    StudentProfilePhotoView,
    StudentProfileView,
    StudentQuestionOptionsView,
    StudentResultDetailView,
    StudentResultDownloadView,
    StudentResultReviewView,
    StudentResultsView,
    SubmitAttemptView,
    UpdateAnswerView,
    ViolationView,
)

urlpatterns = [
    path("profile/", StudentProfileView.as_view()),
    path("profile/photo/", StudentProfilePhotoView.as_view()),
    path("playground/generate/", PlaygroundGenerateView.as_view()),
    path("playground/sessions/", PlaygroundSessionListView.as_view()),
    path("playground/sessions/<uuid:session_id>/", PlaygroundSessionDetailView.as_view()),
    path("playground/sessions/<uuid:session_id>/submit/", PlaygroundSubmitView.as_view()),
    path("playground/summary/", PlaygroundSummaryView.as_view()),
    path("exams/available/", AvailableExamsView.as_view()),
    path("exams/<uuid:exam_id>/start/", StartExamView.as_view()),
    path("attempts/<uuid:attempt_id>/remaining-time/", RemainingTimeView.as_view()),
    path("attempts/<uuid:attempt_id>/answers/", AttemptAnswersView.as_view()),
    path("questions/<uuid:question_id>/options/", StudentQuestionOptionsView.as_view()),
    path("answers/<uuid:answer_id>/", UpdateAnswerView.as_view()),
    path("answers/<uuid:answer_id>/run-code/", RunCodingAnswerView.as_view()),
    path("attempts/<uuid:attempt_id>/submit/", SubmitAttemptView.as_view()),
    path("attempts/<uuid:attempt_id>/auto-submit/", AutoSubmitAttemptView.as_view()),
    path("attempts/<uuid:attempt_id>/violation/", ViolationView.as_view()),
    path("results/", StudentResultsView.as_view()),
    path("results/<uuid:result_id>/", StudentResultDetailView.as_view()),
    path("results/<uuid:result_id>/review/", StudentResultReviewView.as_view()),
    path("results/<uuid:result_id>/download/", StudentResultDownloadView.as_view()),
]
