# Generated by Django 4.2.30 on 2026-04-12

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_scoped_email_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customuser",
            name="uniq_role_email",
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=Q(role__in=["admin", "teacher", "student"]),
                fields=("organization", "role", "email"),
                name="uniq_org_role_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=Q(role="god"),
                fields=("email",),
                name="uniq_god_email",
            ),
        ),
    ]
