# Generated by Django 4.2.30 on 2026-04-13 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attempts', '0002_answer_code_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('requested_question_count', models.PositiveSmallIntegerField(default=5)),
                ('generated_question_count', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('submitted', 'Submitted')], default='generated', max_length=12)),
                ('generator_model', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playground_sessions', to='departments.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playground_sessions', to='departments.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playground_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option_index', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='attempts.playgroundsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.playgroundquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.playgroundsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playgroundquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='uniq_playground_question_session_order'),
        ),
        migrations.AddConstraint(
            model_name='playgroundanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='uniq_playground_answer_session_question'),
        ),
    ]
